
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pp_prod
    username: pp_prod_user
    password: petproject
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false